config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {confirmation: "users/confirmation",omniauth_callbacks: "users/omniauth_callbacks"}
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
 resources :users, only: [:index, :show, :destroy, :edit, :update] do 
    member do 
      patch :ban
      patch :resend_confirmation_instructions
    end
 end
  root "static_pages#landing_page"
  get "privacy_policy", to: "static_pages#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/roleable.rb
module Roleable
    
extend ActiveSupport::Concern 
included do 
    # List User Roles
    ROLES =[:admin, :teacher, :student]
    #Json column to store roles
    store_accessor :roles, *ROLES

    # cast roles to/from booleans
    ROLES.each do |role|
    scope role, -> { where("roles @> ?", {role => true}.to_json)}
    define_method(:"#{role}=") {|value| super ActiveRecord::Type::Boolean.new.cast(value)}
    define_method(:"#{role}?"){send(role)}
    end

    def active_roles # where Value true
        ROLES.select {|role| send(:"#{role}?") }.compact
    end

    # role validation 
    validate :must_have_a_role, on: :update
    validate :must_have_an_admin

    private 
    def must_have_an_admin
        if persisted? && 
            (User.where.not(id: id).pluck(:roles).count { |h| h["admin"] == true}<1 )&& roles_changed? && admin == false
            errors.add(:base, "There should be at least one admin")
        end
    end

    def must_have_a_role
        if roles.values.none?
            errors.add(:base, "A user must have at least one role")
        end
    end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable, :lockable, :invitable,
         :omniauthable, omniauth_providers: [:google_oauth2, :github, :facebook]

 include Roleable
  def self.from_omniauth(access_token)
      data = access_token.info
      user = User.where(email: data['email']).first
          # Uncomment the section below if you want users to be created if they don't exist
      unless user
          user = User.create(
                email: data['email'],
               password: Devise.friendly_token[0,20]
              )
      end
          user.provider=access_token.provider
          user.uid=access_token.uid
          user.name= access_token.info.name
          user.image= access_token.info.image
          user.save
          user.confirmed_at=Time.now # autoconfirm user from omniauth
          user
      end

      after_create do 
        # assign default role student
        self.update(student: true)
      end
    def to_s
        email
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    def after_sign_in_path_for(resource)
        user_path(resource)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:landing_page,:privacy_policy]
  def landing_page
  end

  def privacy_policy
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource) # In case you want to sign in the user
      your_new_after_confirmation_path
      root_path
    end
  end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def google_oauth2
    handle_auth('Google')
  end


  def github
    handle_auth('Github')
  end

  def facebook
    handle_auth('Facebook')
  end
    def handle_auth(kind)
     
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end

  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_admin, only: [:edit, :update, :ban, :destroy]
    def index
       @users=User.all.order(:created_at)
    end

    def show 
        @users = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        if @user.update(user_params)
            redirect_to @user, notice: "User was successfuly updated"
        else 
            render :edit
        end
         
    end

    def resend_confirmation_instructions
        @user = User.find(params[:id])
        unless @user.confirmed?
            @user.resend_confirmation_instructions
            redirect_to @user, notice: "Confirmation Instruction were  resent"
        else
            redirect_to @user, alert: "User already confirmed.."
        end
    
       
    end

    def ban 
        puts "saya"
        @user = User.find(params[:id])
        if @user.access_locked?
            @user.access_locked?
        else
            @user.lock_access!
        end
        redirect_to @user, notice: "User ban status updated"
    end

 
    private

    def user_params
    params.require(:user).permit(*User::ROLES)
    end

    def require_admin
        unless current_user.admin?
            redirect_to root_path, alert: "You are not authorized to perform this action "
        end
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

    def boolean_label (value)
        case value
           when true
             content_tag(:span, value, class: "badge bg-success")
           when false
            content_tag(:span, value, class: "badge bg-danger")
        
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def ban_status(user)
        if user.access_locked?
            "Unban"
        else
            "Ban"
        end
    end
end

app/views/layouts/_header.html.erb
<head>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>



</head>

<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fas fa-flag"></i>
      Brand
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do %>
          <div class="fa fa-home"></div>
          Home
        <% end %>
        <% if current_user %>
        <%= link_to users_path, class: "nav-link #{'active fw-bold' if current_page?(users_path)}" do %>
        <div class="fa fa-users"></div>
        Users
      <% end %>
      <%= link_to "Invite User",new_user_invitation_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_invitation_path)}" %>
      <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="fa fa-user"></div>
              <b><%= current_user.email %></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to user_path(current_user), class: "dropdown-item #{'active fw-bold' if current_page?(user_path(current_user))}" do %>
            <div class="fa fa-cog"></div>
            <b>My Profile</b>
          <% end %>
              <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_message.html.erb
<% if notice.present? %>
<p class="notice bg-success"><%= notice %></p>
<% elsif alert.present?  %>
<p class="alert bg-danger"><%= alert %></p>
<% end %>

<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": true,
                                                  "positionClass": "toast-top-center", 
                                                  "onclick": null, 
                                                  "showDuration": "300", 
                                                  "hideDuration": "1000", 
                                                  "timeOut": "5000", 
                                                  "extendedTimeOut": "1000", 
                                                  "showEasing": "swing", 
                                                  "hideEasing": "linear", 
                                                  "showMethod": "fadeIn", 
                                                  "progressBar": true,
                                                  "hideMethod": "fadeOut" });
    <% end %>
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyGemsBootcamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%= render "layouts/header" %><br><br>
 <%= render "layouts/message" %>
 <div class="container">
    <%= yield %>
  </div>
  </body>
  <footer class="bg-dark text-light">
  <div class="container">
  <br>
  Copyright @ 2021
  </p>
  </div>
  </footer>
</html>

app/views/static_pages/landing_page.html.erb
<div class="container-fluid">

<h1>Hello Word</h1>

<%= link_to privacy_policy_path, class:"btn btn-lg btn-warning"  do%>
    <i class="fas fa-file"></i>
    Privacy Policy
<% end %>
</div>

app/views/static_pages/privacy_policy.html.erb
<h1>StaticPages#privacy_policy</h1>

app/views/users/_user.html.erb
<%- @users.each do |user|  -%>
    <hr>
    <b>ID:</b>
<%= link_to user.id, user_path(user)%>
<br>
<b>Email:</b>
<%= user.email %>
<br>
<b>Confirmation:</b>
<%= user.confirmed? %>
<br>

<b><%= 'sign_in_count'.humanize %></b>
<%= user.sign_in_count %>
<br>
<b><%= 'current_sign_in_at'.humanize %></b>
<%= user.current_sign_in_at.in_time_zone("Asia/Kuala_Lumpur").strftime("%Y-%m-%e %l:%M:%S %p") %>
<br>
<b><%= 'last_sign_in_at'.humanize %></b>
<%= user.last_sign_in_at.in_time_zone("Asia/Kuala_Lumpur").strftime("%Y-%m-%e %l:%M:%S %p") %>
<br>
<b><%= 'current_sign_in_ip'.humanize %></b>
<%= user.current_sign_in_ip %>
<br>
<b><%= 'last_sign_in_ip'.humanize %></b>
<%= user.last_sign_in_ip %>
<br>
<b><%= 'locked_at'.humanize %></b>
<%= (user.locked_at)? user.locked_at.in_time_zone("Asia/Kuala_Lumpur").strftime("%Y-%m-%e %l:%M:%S %p"):'---' %>
<br>
<b><%= 'provider'.humanize %></b>
<%= user.provider %>
<br>
<b><%= 'uid'.humanize %></b>
<%= user.uid %>
<br>
<b><%= 'name'.humanize %></b>
<%= user.name %>
<br>
<b><%= 'image'.humanize %></b>
<% if user.image.present? %>
<%=  image_tag user.image, size: "50x50" %>
<% end %>
<br>
<b><%= 'role'.humanize %></b>
<%= user.active_roles.join(",") %>
<br>

<%= link_to ban_status(user), ban_user_path(user),method: :patch ,class:"btn btn-sm btn-danger" %>
<%= link_to "Edit roles", edit_user_path(user),class:"btn btn-sm btn-warning"  %>
<%= link_to "Delete",user, data:{confirm: "Are you sure?"}, :method => :delete, class:"btn btn-sm btn-danger" %>

<% end %>

app/views/users/edit.html.erb
<div class="card">
<div class="card-header">
<h2>Editing roles for <%= @user %></h2>
</div>
<div class="card-body">
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
    <h2> 
     <%= pluralize(@user.errors.count, "error") %>
     prohibited this user from being saved:
    </h2>
    <ul>
    <% @user.errors.full_messages.each do |message|%>
        <li><%= message %></li>
    <% end %>
    </ul>
    </div>
    <% end %>

    <% User::ROLES.each do |role| %>
        <label>
        <%= f.check_box role %>
        <%= role.to_s.humanize %>
        </label>
        <br>
    <% end %>
    <%= f.button :submit %>
<% end %>
</div>
<div class="card-footer">
<%= link_to "Cancel", user_path(@user) %>
</div>
</div>
</div>

app/views/users/index.html.erb
 <h2>User:</h2>
<%= @users.size  %>
<div class="table-responsive">
<table class="table table-striped table-hover table-sm">
     <thead>
         <tr>
             <th>ID </th>
             <th>Email</th>
             <th>Confirmed</th>
             <th>Banned?</th>
             <th>Name</th>
             <th>Images</th>
             <th>Roles</th>
             <th>Create Invite?</th>
             <th>Invitation Accepted?</th>
             <th colspan="3">Action</th>
         </tr>
    </thead>
    <tbody>
          <%- @users.each do |user|  -%>
            <tr>
            <td><%= link_to user.id, user_path(user)%></td>
            <td><%= user.email %></td>
            <td><%= boolean_label(user.confirmed?) %>
               <% unless user.confirmed? %>
               <%= link_to "Resend Confirmation Instruction", resend_confirmation_instructions_user_path(user), method: :patch %>
               <% end %>
               <%= link_to "Resend Confirmation Instruction", resend_confirmation_instructions_user_path(user), method: :patch %>
            </td>
            <td><%= boolean_label(user.access_locked?) %></td>
            <td><%= user.name %></td>
            <td><% if user.image.present? %>
            <%=  image_tag user.image, size: "50x50" %>
            <% end %></td>
            <td><%= user.active_roles.join(",") %></td>
            <td><%= boolean_label(user.created_by_invite?) %></td>
            <td><%= boolean_label(user.invitation_accepted?) %></td>
            <td>
                <%= link_to "Edit roles", edit_user_path(user), class:"btn btn-sm btn-warning"  %>
                <%= link_to ban_status(user), ban_user_path(user),method: :patch, class:"btn btn-sm btn-danger"  %>
                <%= link_to "Delete",user, data:{confirm: "Are you sure?"}, :method => :delete, class:"btn btn-sm btn-danger" %>
            </td>
        
            </tr>
           <% end %>
     </tbody>
</table>
</div>

app/views/users/show.html.erb
<div class="card">
<div class="card-body">
<b>ID:</b>
<%= @users.id %>
<br>
<b>Email:</b>
<%= @users.email %>
<br>
<b>Confirmation:</b>
<%= @users.confirmed? %>
<br>
<b>Sign In Count:</b>
<%= @users.sign_in_count %>
<br>
<b>Current Sign  In :</b>
<%= @users.current_sign_in_at.in_time_zone("Asia/Kuala_Lumpur").strftime("%Y-%m-%e %l:%M:%S %p") %>
<br>
<b>Last Sign In :</b>
<%= @users.last_sign_in_at.in_time_zone("Asia/Kuala_Lumpur").strftime("%Y-%m-%e %l:%M:%S %p") %>
<br>
<b>Current Sign In IP :</b>
<%= @users.current_sign_in_ip %>
<br>
<b>Last Sign In IP :</b>
<%= @users.last_sign_in_ip %>
<br>
<b>Locked At :</b>
<%= (@users.locked_at)? @users.locked_at.in_time_zone("Asia/Kuala_Lumpur").strftime("%Y-%m-%e %l:%M:%S %p") : '----' %>
<br>
<b>Provider: </b>
<%= (@users.provider)? @users.provider: '----' %>
<br>
<b>Uid:</b>
<%= @users.uid %>
<br>
<b>Name:</b>
<%= @users.name %>
<br>
<b>Roles:</b>
<%= @users.active_roles.join(",") %><br>
<%= link_to "Edit roles", edit_user_path(@users), class:"btn btn-sm btn-warning"  %>
<%= link_to ban_status(@users), ban_user_path(@users),method: :patch, class:"btn btn-sm btn-danger"  %>
<%= link_to "Delete",@users, data:{confirm: "Are you sure?"}, :method => :delete, class:"btn btn-sm btn-danger" %><br>
</div>
<div class="card-footer">
<%= link_to "All User", users_path(@users) %>
</div>
</div>